apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name}}
type: kubernetes.io/basic-auth
stringData:
  database: {{ .Values.secret.database}}
  username: {{ .Values.appName}}
  password: {{ .Values.appName}}